name: base
in_c: ${dataset.img_chls}
out_c: ${dataset.img_chls}
init_c: 128
chls_mult_factor: [1, 2, 2, 4]
has_attn: [false, false, false, true]
num_res_blocks: 2
num_attn_heads: 4
dropout: 0.1
t_emb_dim: 512
n_classes: ${dataset.n_classes}